// put your code here
// remember, you can use modules with browserify
var foo = require('./foo');
console.log(foo);
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
console.log('apa2')
